### ISSUE TITLE
Email PDF to clinician

### ISSUE THREAD

**Issue by RhodesPeter** [CYPIAPT-LNDSE/welcome-to-camhs#70]
We need to create some code which will safely offer the user the ability to email their therapist the pdf which is generated at the end of the questionnaire.

**Comment by MHemsley** [comment]
Hi Peter, 
I discussed with Bradley this morning, but for this to be useful across trusts we need to send a CSV as well as a PDF.




Get Outlook for Android





On Mon, Mar 6, 2017 at 3:49 PM +0000, "Peter Rhodes" 
<notifications@github.com> wrote:



We need to create some code which will safely offer the user the ability to email their therapist the pdf which is generated at the end of the questionnaire.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.






{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CYPIAPT-LNDSE/welcome-to-camhs","title":"CYPIAPT-LNDSE/welcome-to-camhs","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CYPIAPT-LNDSE/welcome-to-camhs"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Email PDF to clinician (#70)"}],"action":{"name":"View Issue","url":"https://github.com/CYPIAPT-LNDSE/welcome-to-camhs/issues/70"}}}



  This email has been scanned for email related threats and delivered safely by Mimecast. For more information please visit http://www.mimecast.com

**Comment by RhodesPeter** [comment]
This issue has been fixed with commit 5ff83f2540832f19beacdb5f6ca85682b77962f3. As has been discussed the clinician will receive an email with the information and not a pdf.
