### ISSUE TITLE
Create tests

### ISSUE THREAD

**Issue by RhodesPeter** [CYPIAPT-LNDSE/welcome-to-camhs#74]
Which testing technology should we be using? 

We are leaning towards Nightwatch.js

**Comment by MHemsley** [comment]
Why Nightwatch? As long as you can define why you want to use a testing technology and the type of testing you will be doing with it, I'm not heavily opinionated on what you use.

**Comment by RhodesPeter** [comment]
We have spoken to @des-des and we are going to unit test our front end javascript.

**Comment by des-des** [comment]
I think nightwatch can come later. It is quite a lot of work and only really becomes really useful when your app grows quite large

**Comment by MHemsley** [comment]
What I would encourage for anything that isn’t implemented in these sprints/not entirely needed, is for the technology / reason for use / reason not implemented to be documented


On 7 Mar 2017, at 17:20, Eoin McCarthy <notifications@github.com> wrote:


I think nightwatch can come later. It is quite a lot of work and only really becomes really useful when your app grows quite large
—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.







{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CYPIAPT-LNDSE/welcome-to-camhs","title":"CYPIAPT-LNDSE/welcome-to-camhs","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/CYPIAPT-LNDSE/welcome-to-camhs" class="">https://github.com/CYPIAPT-LNDSE/welcome-to-camhs</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@des-des in #74: I think nightwatch can come later. It is quite a lot of work and only really becomes really useful when your app grows quite large"}],"action":{"name":"View Issue","url":"<a href="https://github.com/CYPIAPT-LNDSE/welcome-to-camhs/issues/74#issuecomment-284792875" class="">https://github.com/CYPIAPT-LNDSE/welcome-to-camhs/issues/74#issuecomment-284792875</a>"}}}




  This email has been scanned for email related threats and delivered safely by Mimecast. For more information please visit http://www.mimecast.com

**Comment by RhodesPeter** [comment]
I am closing this issue as we have created all of the tests that we intend to create for sprint 2. 


![screen shot 2017-04-20 at 11 52 07](https://cloud.githubusercontent.com/assets/18164707/25227233/cd30ff20-25bf-11e7-8c7d-4ff398577125.png)

If further work is made on this project in the future this issue should be reopened.
